### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by Coopyy** [KleskBY/KleskBY-base#1]
no no no no no
gdi is most certainly not the best option. Try GameOverlay.net, or SharpDX

**Comment by KleskBY** [comment]
GameOverlay.net = -80 fps without drawing;
SharpDX =-30 fps but many additional libs and code.
GDI = -40 fps;

**Comment by Coopyy** [comment]
something wrong on your end my guy, i hit 2000 frames on overlay and 300 in game with a gtx 970
